Repository Team-Symphony/Melody, pull requests merged in 2024-10, with the labels that each got.

#5 Add Netherite Horse Armor
  src/main/java/dev/symphony/melody/Melody.java
  src/main/java/dev/symphony/melody/config/MelodyConfig.java
  src/main/java/dev/symphony/melody/config/MelodyConfigCondition.java
  src/main/java/dev/symphony/melody/item/ModArmorMaterials.java
  src/main/java/dev/symphony/melody/item/ModItemGroups.java
  src/main/java/dev/symphony/melody/item/ModItems.java
  src/main/resources/assets/melody/lang/en_us.json
  src/main/resources/assets/melody/models/item/netherite_horse_armor.json
  src/main/resources/assets/melody/textures/item/netherite_horse_armor.png
  src/main/resources/assets/minecraft/textures/entity/horse/armor/horse_armor_netherite.png
  src/main/resources/data/melody/recipe/netherite_horse_armor_smithing.json
Labels: feature: transport

#7 Rename netherite horse armor texture to fix it not loading
  src/main/resources/assets/melody/textures/entity/horse/armor/horse_armor_netherite_horse_armor_material.png
Labels: minor bug

#4 Add VehiclesMoveThroughLeaves
  src/main/java/dev/symphony/melody/config/MelodyConfig.java
  src/main/java/dev/symphony/melody/mixin/transportation/VehiclesMoveThroughLeaves.java
  src/main/resources/melody.mixins.json
Labels: feature: transport

#8 Add Map Book
  src/client/java/dev/symphony/melody/MelodyClient.java
  src/client/java/dev/symphony/melody/ModModelPredicates.java
  src/client/java/dev/symphony/melody/map_book/MapBookScreen.java
  src/client/java/dev/symphony/melody/map_book/MapTile.java
  src/client/java/dev/symphony/melody/mixin/client/map_book/CartographyTableScreenMixin.java
  src/client/java/dev/symphony/melody/mixin/client/map_book/HeldMapBookRenderingMixin.java
  src/client/java/dev/symphony/melody/mixin/client/map_book/MapPositionRequestMixin.java
  src/client/java/dev/symphony/melody/network/ClientSyncHandler.java
  src/client/resources/melody.client.mixins.json
  src/main/java/dev/symphony/melody/Melody.java
  src/main/java/dev/symphony/melody/config/MelodyConfig.java
  src/main/java/dev/symphony/melody/config/MelodyConfigCondition.java
  src/main/java/dev/symphony/melody/item/ModArmorMaterials.java
  src/main/java/dev/symphony/melody/item/ModItemGroups.java
  src/main/java/dev/symphony/melody/item/ModItems.java
  src/main/java/dev/symphony/melody/item/ModRecipes.java
  src/main/java/dev/symphony/melody/item/map_book/MapBookAdditionRecipe.java
  src/main/java/dev/symphony/melody/item/map_book/MapBookAdditionsComponent.java
  src/main/java/dev/symphony/melody/item/map_book/MapBookCloningRecipe.java
  src/main/java/dev/symphony/melody/item/map_book/MapBookIdCountsState.java
  src/main/java/dev/symphony/melody/item/map_book/MapBookItem.java
  src/main/java/dev/symphony/melody/item/map_book/MapBookState.java
  src/main/java/dev/symphony/melody/item/map_book/MapBookStateManager.java
  src/main/java/dev/symphony/melody/item/map_book/MapStateAccessor.java
  src/main/java/dev/symphony/melody/item/map_book/MapStateData.java
  src/main/java/dev/symphony/melody/mixin/map_book/CartographyRecipesMixin.java
  src/main/java/dev/symphony/melody/mixin/map_book/CartographyRecipesSlot0Mixin.java
  src/main/java/dev/symphony/melody/mixin/map_book/CartographyRecipesSlot1Mixin.java
  src/main/java/dev/symphony/melody/mixin/map_book/MapStateMixin.java
  src/main/java/dev/symphony/melody/network/IntArray.java
  src/main/java/dev/symphony/melody/network/MapBookOpenPayload.java
  src/main/java/dev/symphony/melody/network/MapBookSyncPayload.java
  src/main/java/dev/symphony/melody/network/MapPositionPayload.java
  src/main/java/dev/symphony/melody/network/MapPositionRequestPayload.java
  src/main/resources/assets/melody/lang/en_us.json
  src/main/resources/assets/melody/models/item/map_book.json
  src/main/resources/assets/melody/models/item/map_book_empty.json
  src/main/resources/assets/melody/textures/item/map_book.png
  src/main/resources/assets/melody/textures/item/map_book_empty.png
  src/main/resources/data/melody/recipe/empty_map_book.json
  src/main/resources/data/melody/recipe/map_book_addition.json
  src/main/resources/data/melody/recipe/map_book_cloning.json
  src/main/resources/melody.mixins.json
Labels: feature: exploration
